/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NFS_H_RPCGEN
#define _NFS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct directory_contents {
	char dir_contents[1000];
};
typedef struct directory_contents directory_contents;

struct directory_name {
	char dir_name[100];
};
typedef struct directory_name directory_name;

#define get_contents_prog 0x23456789
#define get_contents_vers 2

#if defined(__STDC__) || defined(__cplusplus)
#define get_contents 1
extern  directory_contents * get_contents_2(directory_name *, CLIENT *);
extern  directory_contents * get_contents_2_svc(directory_name *, struct svc_req *);
extern int get_contents_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_contents 1
extern  directory_contents * get_contents_2();
extern  directory_contents * get_contents_2_svc();
extern int get_contents_prog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_directory_contents (XDR *, directory_contents*);
extern  bool_t xdr_directory_name (XDR *, directory_name*);

#else /* K&R C */
extern bool_t xdr_directory_contents ();
extern bool_t xdr_directory_name ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NFS_H_RPCGEN */
