/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"
#include <string.h>
#include <dirent.h>
#include <stdlib.h>


directory_contents *
get_contents_2_svc(directory_name *argp, struct svc_req *rqstp)
{
	static directory_contents  result;
	char dir_name[100]; strcpy(dir_name,argp->dir_name);
	struct dirent **namelist; 
	/*
	 * insert server code here
	 */
	int n;
	n = scandir(dir_name,&namelist,NULL,alphasort);
	if(n<0)
	{
		perror("scandir \n"); 
	}
	else
	{
		
		while(n--)
		{
			strcat(result.dir_contents,namelist[n]->d_name); strcat(result.dir_contents,"\n");
		}
		
	}
	return &result;
}
