/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"
#include <string.h>

void
get_contents_prog_2(char *host,char dir[])
{
	CLIENT *clnt;
	directory_contents  *result_1;
	directory_name  get_contents_2_arg;
	strcpy(get_contents_2_arg.dir_name,dir);
#ifndef	DEBUG
	clnt = clnt_create (host, get_contents_prog, get_contents_vers, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = get_contents_2(&get_contents_2_arg, clnt);
	if (result_1 == (directory_contents *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		int i;
		printf("%s\n",result_1->dir_contents );
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char dir[100];
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	printf("Enter the name of the directory \n"); scanf("%s",dir);
	get_contents_prog_2 (host,dir);
exit (0);
}
