/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"


void
date_prog_1(char *host)
{
	CLIENT *clnt;
	long  *result_1;
	
	long *lresult;
	char **sresult;

#ifndef	DEBUG
	clnt = clnt_create (host, DATE_PROG, DATE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	lresult = bin_date_1(NULL, clnt);
	if (lresult == (long *) NULL) {
		clnt_perror (clnt, host);
	}
	else
	{
		printf("Time on host %s = %ld \n",host,*lresult );
	}
	sresult = str_date_1(lresult, clnt);
	if (sresult == (char **) NULL) {
		clnt_perror (clnt, host);
	}
	else
	{
		printf("Time on host %s = %s \n",host,*sresult );
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	date_prog_1 (host);
exit (0);
}
