/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"
#include <string.h>

void
read_file_prog_2(char *host,char filename[])
{
	CLIENT *clnt;
	data  *result_1;
	data  get_file_contents_2_arg;
	strcpy(get_file_contents_2_arg.arr,filename);
#ifndef	DEBUG
	clnt = clnt_create (host, READ_FILE_PROG, READ_FILE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = get_file_contents_2(&get_file_contents_2_arg, clnt);
	if (result_1 == (data *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
	
		printf("%s\n",result_1->arr );
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char filename[100];
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	printf("Enter the name of the file \n");	scanf("%s",filename);
	read_file_prog_2 (host,filename);
exit (0);
}
