/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "nfs.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>

data *
get_file_contents_2_svc(data *argp, struct svc_req *rqstp)
{
	static data  result;
	printf("READ_FILE(%s) called \n",argp->arr );
	char ch;
	int i=0;
	/*
	 * insert server code here
	 */
	int rfd = open(argp->arr,'r');
	dup2(rfd,0);
	while(scanf("%c",&ch)>0)
	{
		printf("%c",ch );
		result.arr[i++]=ch;
	}
	return &result;
}
