/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "arr_sum.h"

int *
get_arr_sum_2_svc(data *argp, struct svc_req *rqstp)
{
	static int  result=0;
	printf("ADD_ARR(array,sum) called \n");
	/*
	 * insert server code here
	 */
	int i;
	for(i=0;i<argp->arr_size;i++) result+=argp->arr_pointer[i];
	return &result;
}
