/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ARR_SUM_H_RPCGEN
#define _ARR_SUM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	int arr_size;
	int *arr_pointer;
};
typedef struct data data;

#define ARR_SUM_PROG 0x23456789
#define ARR_SUM_VERS 2

#if defined(__STDC__) || defined(__cplusplus)
#define get_arr_sum 1
extern  int * get_arr_sum_2(data *, CLIENT *);
extern  int * get_arr_sum_2_svc(data *, struct svc_req *);
extern int arr_sum_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_arr_sum 1
extern  int * get_arr_sum_2();
extern  int * get_arr_sum_2_svc();
extern int arr_sum_prog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ARR_SUM_H_RPCGEN */
