/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "arr_sum.h"

int *
get_arr_sum_2_svc(data *argp, struct svc_req *rqstp)
{
	printf("ADD_ARR(array,size )\n");
	static int  result=0;
	int i,sz,*ptr;
	sz = argp->arr_size; ptr = argp->arr_pointer;
	printf("Size of array passed = %d \n", sz);
	for(i=0;i<argp->arr_size;i++) 
	{
		printf("Adding %d \n",ptr[i] ); result+=ptr[i];
	}
	/*
	 * insert server code here
	 */

	return &result;
}
