/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "arr_sum.h"
#include <stdio.h>
#include <stdlib.h>

void
arr_sum_prog_2(char *host,int sz,int* ptr)
{
	CLIENT *clnt;
	int  *result_1;
	int i;
	data  get_arr_sum_2_arg;
	get_arr_sum_2_arg.arr_size = sz;
	get_arr_sum_2_arg.arr_pointer = (int*)malloc(sz*sizeof(int));
	for(i=0;i<sz;i++) get_arr_sum_2_arg.arr_pointer[i] = ptr[i];
#ifndef	DEBUG
	clnt = clnt_create (host, ARR_SUM_PROG, ARR_SUM_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = get_arr_sum_2(&get_arr_sum_2_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("Sum of elements : %d \n",*result_1 );
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int i,sz; int* ptr;
	printf("Enter the number of numbers \n"); scanf("%d",&sz);
	int l = sizeof(int);
	ptr = (int*)malloc(sz*l);
	for(i=0;i<sz;i++) scanf("%d",ptr+i);
	arr_sum_prog_2 (host,sz,ptr);
exit (0);
}
